services:
  auth-db:
    container_name: auth-db
    image: mariadb:latest
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME_AUTH}"
      MARIADB_PASSWORD: "${DB_PASSWORD_AUTH}"
      MARIADB_DATABASE: "${DB_NAME_AUTH}"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /home/toughcircle/auth_db_data:/var/lib/mysql
    networks:
      - my_network  # 네트워크 추가

  resource-db:
    container_name: resource-db
    image: mariadb:latest
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME_RESOURCE}"
      MARIADB_PASSWORD: "${DB_PASSWORD_RESOURCE}"
      MARIADB_DATABASE: "${DB_NAME_RESOURCE}"
    restart: unless-stopped
    ports:
      - "3307:3307"
    volumes:
      - /home/toughcircle/resource_db_data:/var/lib/mysql
    networks:
      - my_network

  auth-server:
    build:
      context: /home/toughcircle/app/deploy/auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    environment:
      DATASOURCE_URL: "${MARIADB_URL_AUTH}"
      DATASOURCE_USERNAME: "${DB_USERNAME_AUTH}"
      DATASOURCE_PASSWORD: "${DB_PASSWORD_AUTH}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - auth-db
    ports:
      - "8888:8888"
    networks:
      - my_network

  resource-server:
    build:
      context: /home/toughcircle/app/deploy/resource-server
      dockerfile: Dockerfile
    container_name: resource-server
    environment:
      DATASOURCE_URL: "${MARIADB_URL_RESOURCE}"
      DATASOURCE_USERNAME: "${DB_USERNAME_RESOURCE}"
      DATASOURCE_PASSWORD: "${DB_PASSWORD_RESOURCE}"
      API_KEY: "${API_KEY}"
      JWT_SECRET: "${JWT_SECRET}"
      GRPC_AUTH_SERVER_URL: "auth-server:50051"
    depends_on:
      - resource-db
      - auth-server
    ports:
      - "9999:9999"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
