version: "3.9"
services:
  auth-db:
    container_name: auth-db
    image: mariadb:latest
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME_AUTH}"
      MARIADB_PASSWORD: "${DB_PASSWORD_AUTH}"
      MARIADB_DATABASE: "${DB_NAME_AUTH}"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/auth_db_data:/var/lib/mysql

  resource-db:
    container_name: resource-db
    image: mariadb:latest
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME_RESOURCE}"
      MARIADB_PASSWORD: "${DB_PASSWORD_RESOURCE}"
      MARIADB_DATABASE: "${DB_NAME_RESOURCE}"
    restart: unless-stopped
    ports:
      - "3307:3307"
    volumes:
      - /home/ubuntu/resource_db_data:/var/lib/mysql

  auth-server:
    build:
      context: /home/ubuntu/app/deploy/auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    environment:
      DATASOURCE_URL: "jdbc:mariadb://auth-db:3306/${DB_NAME_AUTH}"
      DATASOURCE_USERNAME: "${DB_USERNAME_AUTH}"
      DATASOURCE_PASSWORD: "${DB_PASSWORD_AUTH}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - auth-db
    ports:
      - "8081:8081"

  resource-server:
    build:
      context: /home/ubuntu/app/deploy/resource-server
      dockerfile: Dockerfile
    container_name: resource-server
    environment:
      DATASOURCE_URL: "jdbc:mariadb://resource-db:3307/${DB_NAME_RESOURCE}"
      DATASOURCE_USERNAME: "${DB_USERNAME_RESOURCE}"
      DATASOURCE_PASSWORD: "${DB_PASSWORD_RESOURCE}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - resource-db
    ports:
      - "8082:8082"
