version: "3.9"
services:
  auth-db:
    container_name: auth-db
    image: mariadb:latest
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME_AUTH}"
      MARIADB_PASSWORD: "${DB_PASSWORD_AUTH}"
      MARIADB_DATABASE: "${DB_NAME_AUTH}"
    restart: unless-stopped
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=${DB_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/ubuntu/auth_db_data:/var/lib/mysql

  resource-db:
    container_name: resource-db
    image: mariadb:latest
    environment:
      TZ: Asia/Jakarta
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MARIADB_USER: "${DB_USERNAME_RESOURCE}"
      MARIADB_PASSWORD: "${DB_PASSWORD_RESOURCE}"
      MARIADB_DATABASE: "${DB_NAME_RESOURCE}"
    restart: unless-stopped
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=${DB_ROOT_PASSWORD}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/ubuntu/resource_db_data:/var/lib/mysql

  auth-server:
    build:
      context: /home/ubuntu/app/deploy/auth-server  # auth-server의 Dockerfile 경로 설정
      dockerfile: Dockerfile
    container_name: auth-server
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://auth-db:3306/${DB_NAME_AUTH}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME_AUTH}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD_AUTH}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      auth-db:
        condition: service_healthy
    ports:
      - "8081:8081"

  resource-server:
    build:
      context: /home/ubuntu/app/deploy/resource-server  # resource-server의 Dockerfile 경로 설정
      dockerfile: Dockerfile
    container_name: resource-server
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://resource-db:3306/${DB_NAME_RESOURCE}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME_RESOURCE}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD_RESOURCE}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      resource-db:
        condition: service_healthy
    ports:
      - "8082:8082"
