server:
  port: 8888

spring:
  application:
    name: auth-server
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 3600000
      refresh-expiration: 604800000

logging:
  level:
    root: INFO
    org.hibernate: DEBUG

grpc:
  server:
    port: 50051

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /swagger-ui.html