server:
  port: 9999

spring:
  application:
    name: resource-server
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: update
    show-sql: true

  task:
    scheduling:
      enabled: true

grpc:
  server:
    port: 50052

logging:
  level:
    root: INFO
    org.hibernate: DEBUG

springdoc:
  api-docs:
    path: /resource-api-docs
  swagger-ui:
    path: /resource-swagger-ui.html
    display-query-params: true
    operationsSorter: alpha

api:
  key: ${API_KEY}  # 실제 API 키
  url: https://www.goldapi.io/api  # 베이스 URL
