name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/libs/*.jar

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy with Docker Compose on EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: 'ubuntu'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            # 기존 컨테이너 중지
            docker-compose stop
            # 새로 컨테이너 시작 및 빌드 (볼륨 유지)
            docker-compose up -d --build
