name: Deploy to Dev Environment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew in auth-server
        run: chmod +x auth-server/gradlew

      - name: Build auth-server
        working-directory: ./auth-server
        run: ./gradlew clean build

      - name: Copy auth-server JAR and Dockerfile to deploy directory
        run: |
          mkdir -p deploy/auth-server
          cp ./auth-server/build/libs/*.jar ./deploy/auth-server/
          cp ./auth-server/Dockerfile ./deploy/auth-server/

      - name: Grant execute permission for gradlew in resource-server
        run: chmod +x resource-server/gradlew

      - name: Build resource-server
        working-directory: ./resource-server
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: ./gradlew clean build

      - name: Copy resource-server JAR and Dockerfile to deploy directory
        run: |
          mkdir -p deploy/resource-server
          cp ./resource-server/build/libs/*.jar ./deploy/resource-server/
          cp ./resource-server/Dockerfile ./deploy/resource-server/

      - name: Copy Docker Compose to deploy directory
        run: |
          cp ./docker-compose.yml ./deploy/
          echo "Contents of deploy directory:"
          ls ./deploy

      - name: Transfer deploy directory to GCP VM Instance
        uses: appleboy/scp-action@v0.1.3
        with:
          username: toughcircle
          host: ${{ secrets.GCP_VM_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./deploy/
          target: /home/toughcircle/app/
          strip_components: 0
          overwrite: true

      - name: Deploy Application on GCP VM via SSH
        uses: appleboy/ssh-action@master
        with:
          username: toughcircle
          host: ${{ secrets.GCP_VM_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/toughcircle/app/deploy

            docker-compose stop || echo "docker-compose stop 실패"

            docker-compose up -d --build || echo "docker-compose up 실패"
